version: '3.8'

services:
  api:
    image: ghcr.io/carlosanamurov/prueba_fino/fastapi-app:latest  # Usa la imagen de GHCR
    restart: always
    environment:
      # Configuración BD Local (MySQL en Docker)
      - DB_HOST=mysql-container-1
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      
      # Configuración BD Remota (Variables desde Secrets)
      - DB_REMOTE_HOST=${DB_REMOTE_HOST}
      - DB_REMOTE_USER=${DB_REMOTE_USER}
      - DB_REMOTE_PASSWORD=${DB_REMOTE_PASSWORD}
      - DB_REMOTE_NAME=${DB_REMOTE_NAME}
      
      # Entorno FastAPI
      - FASTAPI_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      mysql-container-1:
        condition: service_healthy
    networks:
      - backend_network

  mysql-container-1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen persistente para producción
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge