version: '3.8'

services:
  api:
    build: .
    image: ghcr.io/carlosanamurov/prueba_fino/fastapi-app:latest
    environment:
      - DB_HOST=mysql-container-1
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      mysql-container-1:
        condition: service_healthy
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql-container-1:
    image: mysql:8.0
    env_file: .env.prod  # Esto es crucial
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge